name: Frontend CI/CD Actions

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    steps: 

    - name: checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync S3 Bucket
      run: aws s3 sync ../../src/frontend/bucket $S3_BUCKET --follow-symlinks
      env: 
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    
    - name: Invalidate Cloudfront Distribution
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_ID }} --paths "/"
